name=ECEUltimateThreadChallenge
version=0.1.0
author=Max Zhu
maintainer=Max Zhu <maxzhu143@gmail.com>
sentence=ESP32 and ESP8266 Spotify API Wrapper
paragraph=A library to wrap the Spotify API. This does not play music! It can be used to see what is currently playing and control the player.
category=Communication
url=https://github.com/maxzhu143/ECEUltimateThreadChallenge
architectures=*